### ISSUE TITLE
"ValueError: No JSON object could be decoded" on 'Run all' an empty test list

### ISSUE THREAD

**Issue by psam44** [beeware/cricket#36]
Sure, not very useful to 'Run all' an empty test tree :) but ....
Just because on command line I'm used to run `manage.py test myapp`
and it's not so explicit in the Django doc that I have to create myself a project/tests.py containing `from myapp.tests import *`.

cricket-django.exe

``` python
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python27\lib\lib-tk\Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "D:\Python27\lib\lib-tk\Tkinter.py", line 533, in callit
    func(*args)
  File "D:\Python27\lib\site-packages\cricket-0.2.4.dev-py2.7.egg\cricket\view.py", line 784, in on_testProgress
    if self.executor and self.executor.poll():
  File "D:\Python27\lib\site-packages\cricket-0.2.4.dev-py2.7.egg\cricket\executor.py", line 225, in poll
    pre = json.loads(line)
  File "D:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "D:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by freakboy3742** [comment]
Closing - this looks like it was fixed with #45
